#!/usr/bin/env bash

set -e

# Install brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Make sure brew is up to date
brew update
brew upgrade

# Check that everything is ok with the system config
brew doctor

# Install command line tools
brew install git
brew install Caskroom/cask/java
brew install maven
brew install node
brew install npm
brew install rpm
brew install rpmbuild
brew install mtr
brew install ssh-copy-id
brew install michaeldfallen/formula/git-radar

# Install cask so that we can install standard apps
brew install caskroom/cask/brew-cask
brew cask install iterm2
brew cask install slack
brew cask install dropbox
brew cask install vlc
brew cask install spotify
brew cask install firefox
brew cask install google-hangouts
brew cask install chitchat
brew cask install github-desktop
brew cask install evernote
brew cask install the-unarchiver
brew cask install outbank
brew cask install vagrant
brew cask install forklift
brew cask install google-chrome
brew cask install 1password
brew cask install tunnelblick
brew cask install vagrant
brew cask install virtualbox
brew cask install twitter
brew linkapps
brew cleanup
